dataset: miniimagenet
backbone: custom_resnet12 
metric: cosine 
recon: l2 
trainer_type: bifurcated 
tester_type: bifurcated 
emb_enhance: True 
weighted_mean: True 
temperature: null 
z_dim: 640
ab_module_layers: [200, 100]
lambdas: [0.0001, 1, 10]
episodes_per_epoch_train: 100
episodes_test: 600
n: 5
k: 5
q: 30
epoch: 2000
lr: 1e-3
weight_decay: 1e-4
weight_decay_clf: 5e-4
lr_gamma: 0.5
img_cols: 84
img_rows: 84
schedular: 400
rank: 3
val_check: 10000
model_id: rel_net_post_emh_resent12
#relnet
clf_mode: rel_net
lr_decoder: 1e-4
pre_emh: False
output_dir: models/output/