dataset: miniimagenet
backbone: custom_resnet12 
metric: cosine 
recon: l2 
trainer_type: bifurcated 
tester_type: bifurcated 
emb_enhance: True 
weighted_mean: True 
temperature: null 
z_dim: 640
ab_module_layers: [200, 100]
lambdas: [0.0001, 1, 10]
episodes_per_epoch_train: 50
episodes_test: 600
n: 5
k: 5
q: 60
epoch: 1000
lr: 1e-2
weight_decay: 0
weight_decay_clf: 0
lr_gamma: 0.1
img_cols: 84
img_rows: 84
schedular: 400
rank: 1
val_check: 20000
model_id: rel_net_ce_resent12_lr1e2_q60
#relnet
clf_mode: rel_net_ce
lr_decoder: 1e-3
pre_emh: False
output_dir: models/output/